version: 2
updates:
  - package-ecosystem: npm
    directory: '/backend'
    schedule:
      interval: daily
    reviewers:
      - @yeelsto/dev-team
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: yarn
    directory: '/frontend'
    schedule:
      interval: daily
    reviewers:
      - @yeelsto/dev-team
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    reviewers:
      - @yeelsto/dev-team
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
